# Generated by Django 4.2 on 2023-05-16 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_aie', models.CharField(max_length=200)),
                ('date_aie', models.DateField()),
                ('periode_phase', models.CharField(max_length=500)),
                ('titre', models.CharField(max_length=500)),
                ('complement', models.CharField(max_length=500, verbose_name='Complement du titre/ ouvrages')),
                ('statut', models.CharField(choices=[('En cours', 'En cours'), ('Classé', 'Classé')], max_length=500)),
                ('redacteur', models.CharField(max_length=500)),
                ('date_de_diffusion', models.DateField()),
                ('etat_aie', models.CharField(max_length=500)),
                ('redactions', models.FileField(upload_to='Redaction Aie')),
            ],
        ),
        migrations.CreateModel(
            name='RapportConception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
