# Generated by Django 4.2 on 2023-05-16 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Rapports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatutSaisiRapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saisie', models.CharField(choices=[('RICT', 'RICT'), ('RIAOERP', 'RIAOERP'), ('RIAOERT', 'RIAOERT'), ('RIAOIGH', 'RIAOIGH'), ('PreRapSi', 'PreRapSi'), ('RVRAT', 'RVRAT'), ('RVMD', 'RVMD'), ('Revue', 'Revue')], max_length=20)),
                ('libelle', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='rapportconception',
            name='phase',
            field=models.ManyToManyField(to='Rapports.statutsaisirapport', verbose_name='PhaseCode'),
        ),
        migrations.AlterField(
            model_name='aie',
            name='periode_phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Rapports.statutsaisirapport'),
        ),
    ]
