# Generated by Django 4.2 on 2023-05-16 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dashbord', '0010_alter_planaffaire_type_affaire'),
        ('missions', '0004_alter_missions_code_mission'),
        ('IT', '0004_interventiontechniques_and_more'),
        ('Rapports', '0002_statutsaisirapport_rapportconception_phase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapportconception',
            name='complement_titre',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='RapportConceptions', to='Rapports.aie'),
        ),
        migrations.AddField(
            model_name='rapportconception',
            name='description_batiment',
            field=models.ManyToManyField(to='Dashbord.descriptiondubatiment'),
        ),
        migrations.AddField(
            model_name='rapportconception',
            name='interventions_associe',
            field=models.ManyToManyField(to='IT.interventiontechniqueassocie'),
        ),
        migrations.AddField(
            model_name='rapportconception',
            name='missions',
            field=models.ManyToManyField(to='missions.missions'),
        ),
        migrations.AddField(
            model_name='rapportconception',
            name='titre',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Rapports.aie'),
        ),
    ]
