# Generated by Django 4.2 on 2023-05-25 07:22

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dashbord', '0022_remove_planaffaire_intervenant_affaires_intervenant'),
        ('Rapports', '0004_alter_rapportconception_description_batiment'),
    ]

    operations = [
        migrations.CreateModel(
            name='RapportDeVisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objet', models.CharField(max_length=50)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='contenu')),
                ('affaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashbord.affaires')),
            ],
        ),
    ]
