# Generated by Django 4.2 on 2023-05-28 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0007_destination_nom'),
        ('Ouvrages', '0003_alter_ouvrages_libelle'),
        ('Rapports', '0005_rapportdevisite'),
    ]

    operations = [
        migrations.AddField(
            model_name='rapportdevisite',
            name='destination',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='destinations.destination'),
        ),
        migrations.AddField(
            model_name='rapportdevisite',
            name='ouvrage',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Ouvrages.ouvrages'),
        ),
    ]
