# Generated by Django 4.2 on 2023-05-29 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ouvrages', '0005_avisouvrages_image'),
        ('Rapports', '0006_rapportdevisite_destination_rapportdevisite_ouvrage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rapportdevisite',
            name='ouvrage',
        ),
        migrations.AddField(
            model_name='rapportdevisite',
            name='ouvrage',
            field=models.ManyToManyField(to='Ouvrages.ouvrages'),
        ),
    ]
