# Generated by Django 4.2 on 2023-05-21 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        ('collaborateurs', '0002_alter_collaborateurs_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborateurs',
            name='numero_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.services'),
        ),
    ]
