# Generated by Django 4.2 on 2023-05-24 06:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('collaborateurs', '0005_alter_collaborateurs_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborateurs',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
