# Generated by Django 4.2 on 2023-05-24 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('collaborateurs', '0006_alter_collaborateurs_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborateurs',
            name='groups',
            field=models.ManyToManyField(to='auth.group'),
        ),
    ]
