# Generated by Django 4.2 on 2023-05-24 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborateurs', '0007_collaborateurs_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborateurs',
            name='poste_occupe',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
