# Generated by Django 4.2 on 2023-05-24 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collaborateurs', '0010_collaborateurs_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaborateurs',
            name='user',
        ),
    ]
