# Generated by Django 4.2 on 2023-05-24 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaborateurs', '0012_alter_collaborateurs_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collaborateurs',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='collaborateurs',
            name='prenom',
        ),
        migrations.AlterField(
            model_name='collaborateurs',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
