# Generated by Django 4.2 on 2023-05-24 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collaborateurs', '0013_remove_collaborateurs_nom_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='collaborateurs',
            managers=[
            ],
        ),
    ]
