# Generated by Django 4.2 on 2023-05-11 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashbord', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affaires',
            name='intervention_technique',
        ),
    ]
