# Generated by Django 4.2 on 2023-05-11 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dashbord', '0003_affaires_intervention_technique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affaires',
            name='constructeurs',
        ),
        migrations.RemoveField(
            model_name='affaires',
            name='missions',
        ),
    ]
