# Generated by Django 4.2 on 2023-05-12 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0004_alter_missions_code_mission'),
        ('Dashbord', '0004_remove_affaires_constructeurs_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='descriptiondubatiment',
            options={'verbose_name': 'Batiment'},
        ),
        migrations.AddField(
            model_name='affaires',
            name='missions',
            field=models.ManyToManyField(to='missions.missions'),
        ),
        migrations.RemoveField(
            model_name='planaffaire',
            name='destination',
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('description', models.TextField()),
                ('batiment', models.ManyToManyField(related_name='Destinations', to='Dashbord.descriptiondubatiment')),
            ],
        ),
        migrations.AddField(
            model_name='planaffaire',
            name='destination',
            field=models.ManyToManyField(related_name='planaffaires', to='Dashbord.destination'),
        ),
    ]
