# Generated by Django 4.2 on 2023-05-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashbord', '0005_alter_descriptiondubatiment_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planaffaire',
            old_name='numero_affaire',
            new_name='affaire',
        ),
        migrations.AddField(
            model_name='affaires',
            name='numero_affaire',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
    ]
