# Generated by Django 4.2 on 2023-05-12 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dashbord', '0008_remove_planaffaire_libelle_affaire_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planaffaire',
            name='libelle_affaire',
        ),
        migrations.AddField(
            model_name='planaffaire',
            name='affaire',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Dashbord.affaires'),
            preserve_default=False,
        ),
    ]
