# Generated by Django 4.2 on 2023-05-12 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashbord', '0009_remove_planaffaire_libelle_affaire_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planaffaire',
            name='type_affaire',
            field=models.CharField(choices=[('CTC', 'CTC'), ('VT', 'VT')], max_length=500),
        ),
    ]
