# Generated by Django 4.2 on 2023-05-18 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0004_alter_missions_code_mission'),
        ('constructeurs', '0002_entreprise_email'),
        ('IT', '0004_interventiontechniques_and_more'),
        ('Dashbord', '0011_affaires_constructeurs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affaires',
            name='constructeurs',
        ),
        migrations.RemoveField(
            model_name='affaires',
            name='intervention_technique',
        ),
        migrations.RemoveField(
            model_name='affaires',
            name='missions',
        ),
        migrations.AddField(
            model_name='planaffaire',
            name='constructeurs',
            field=models.ManyToManyField(to='constructeurs.entreprise'),
        ),
        migrations.AddField(
            model_name='planaffaire',
            name='intervention_technique',
            field=models.ManyToManyField(to='IT.interventiontechniqueassocie'),
        ),
        migrations.AddField(
            model_name='planaffaire',
            name='missions',
            field=models.ManyToManyField(to='missions.missions'),
        ),
        migrations.AlterField(
            model_name='planaffaire',
            name='risque',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Particulier', 'Particulier'), ('Complexe', 'Complexe')], max_length=200),
        ),
    ]
