# Generated by Django 4.2 on 2023-05-19 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dashbord', '0012_remove_affaires_constructeurs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planaffaire',
            name='affaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affaires', to='Dashbord.affaires'),
        ),
    ]
