# Generated by Django 4.2 on 2023-05-20 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collaborateurs', '0002_alter_collaborateurs_address_and_more'),
        ('Dashbord', '0015_alter_planaffaire_tutorat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planaffaire',
            name='tutorat',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plaaffaires', to='collaborateurs.collaborateurs'),
        ),
    ]
