# Generated by Django 4.2 on 2023-05-22 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashbord', '0017_alter_planaffaire_tutorat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planaffaire',
            name='compte_postal',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
