# Generated by Django 4.2 on 2023-05-22 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dashbord', '0018_alter_planaffaire_compte_postal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planaffaire',
            name='affaire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planaffaires', to='Dashbord.affaires'),
        ),
        migrations.AlterField(
            model_name='planaffaire',
            name='produit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Dashbord.produit'),
        ),
    ]
