# Generated by Django 4.2 on 2023-05-25 04:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Dashbord', '0021_planaffaire_intervenant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planaffaire',
            name='intervenant',
        ),
        migrations.AddField(
            model_name='affaires',
            name='intervenant',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
