# Generated by Django 4.2 on 2023-04-18 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('missions', '0001_initial'),
        ('collaborateurs', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_libelle', models.IntegerField()),
                ('libelle_it', models.CharField(max_length=50)),
                ('libelle_cb', models.CharField(max_length=50)),
                ('code_chantier', models.CharField(max_length=20)),
                ('affectable', models.BooleanField(default=True)),
                ('information', models.DateField(help_text='Affecté le 15/04/23')),
                ('cb_propose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cb_propose', to='services.services')),
                ('nom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collaborateurs.collaborateurs')),
                ('prestation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='missions.prestations')),
            ],
        ),
    ]
