# Generated by Django 4.2 on 2023-05-07 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IT', '0002_rename_it_interventiontechnique'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interventiontechnique',
            old_name='cb_propose',
            new_name='num_service_propose',
        ),
        migrations.RemoveField(
            model_name='interventiontechnique',
            name='libelle_cb',
        ),
        migrations.RemoveField(
            model_name='interventiontechnique',
            name='prestation',
        ),
    ]
