# Generated by Django 4.2 on 2023-05-11 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affaires', '0006_remove_planaffairecreation_missions_and_more'),
        ('Dashbord', '0001_initial'),
        ('Courriers', '0001_initial'),
        ('collaborateurs', '0001_initial'),
        ('Document', '0001_initial'),
        ('services', '0001_initial'),
        ('IT', '0003_rename_cb_propose_interventiontechnique_num_service_propose_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterventionTechniques',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_it', models.CharField(max_length=20)),
                ('libelle_it', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameModel(
            old_name='InterventionTechnique',
            new_name='InterventionTechniqueAssocie',
        ),
    ]
