# Generated by Django 4.2 on 2023-05-21 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IT', '0005_rename_code_chantier_interventiontechniqueassocie_cod_it_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InterventionTechniques',
        ),
    ]
