# Generated by Django 4.2 on 2023-05-11 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0003_alter_destination_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='address',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='destination',
            name='name',
            field=models.CharField(max_length=15),
        ),
    ]
