# Generated by Django 4.2 on 2023-05-12 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashbord', '0005_alter_descriptiondubatiment_options_and_more'),
        ('destinations', '0004_alter_destination_address_alter_destination_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='address',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='city',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='client',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='country',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='longitude',
        ),
        migrations.AddField(
            model_name='destination',
            name='batiment',
            field=models.ManyToManyField(to='Dashbord.descriptiondubatiment'),
        ),
    ]
