# Generated by Django 4.2 on 2023-05-20 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0005_remove_destination_address_remove_destination_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='batiment',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='description',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='name',
        ),
        migrations.AddField(
            model_name='destination',
            name='actions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='destination',
            name='criters',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='destination',
            name='descriptions',
            field=models.CharField(default='', max_length=1500),
        ),
        migrations.AddField(
            model_name='destination',
            name='groupes',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='destination',
            name='type_de_description',
            field=models.CharField(default='', max_length=200),
        ),
    ]
