# Generated by Django 4.2 on 2023-05-20 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0006_remove_destination_batiment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='nom',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
