# Generated by Django 4.2 on 2023-04-18 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Missions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_mission', models.CharField(max_length=10)),
                ('libelle_mission', models.CharField(max_length=500)),
                ('cree_le', models.DateField()),
            ],
            options={
                'verbose_name': 'Mission',
            },
        ),
        migrations.CreateModel(
            name='Prestations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_prestation', models.CharField(max_length=10)),
                ('libelle_prestation', models.CharField(max_length=500)),
                ('cree_le', models.DateField()),
            ],
            options={
                'verbose_name': 'Prestation',
            },
        ),
        migrations.CreateModel(
            name='PrestaionsMissionsSignes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=500)),
                ('cree_le', models.DateField(max_length=500)),
                ('nbre', models.IntegerField(verbose_name='NBIT')),
                ('mission_signe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='missions.missions')),
                ('prestation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='missions.prestations')),
            ],
            options={
                'verbose_name': 'Liste des prestatins signés par mission',
            },
        ),
    ]
