# Generated by Django 4.2 on 2023-05-07 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IT', '0003_rename_cb_propose_interventiontechnique_num_service_propose_and_more'),
        ('missions', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrestaionsMissionsSignes',
        ),
        migrations.DeleteModel(
            name='Prestations',
        ),
    ]
