# Generated by Django 4.2 on 2023-05-11 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0002_delete_prestaionsmissionssignes_delete_prestations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missions',
            name='libelle_mission',
            field=models.CharField(max_length=35),
        ),
    ]
