# Generated by Django 4.2 on 2023-05-11 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0003_alter_missions_libelle_mission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missions',
            name='code_mission',
            field=models.CharField(max_length=3),
        ),
    ]
