# Generated by Django 4.2 on 2023-04-18 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raison_social', models.CharField(blank=True, max_length=500)),
                ('numero_siret', models.CharField(blank=True, max_length=14)),
                ('code_chantier', models.CharField(blank=True, max_length=100)),
                ('mel', models.BooleanField(default=True)),
                ('fax', models.BooleanField(default=False)),
                ('courrier', models.BooleanField(default=False)),
                ('code_postal_pour_envoie_mail', models.BooleanField(blank=True, default=False)),
                ('boite_postal', models.CharField(blank=True, max_length=5)),
                ('bureau_distributeur', models.CharField(max_length=500)),
                ('cedex', models.CharField(max_length=500)),
                ('cplt_geo', models.CharField(max_length=500)),
                ('numero_voie', models.CharField(blank=True, max_length=10, verbose_name='N° et Voie')),
                ('lieu_dit', models.CharField(max_length=500)),
                ('cp', models.CharField(max_length=15)),
                ('ville', models.CharField(max_length=500)),
                ('departement', models.CharField(max_length=500)),
                ('province', models.CharField(max_length=500)),
                ('pays', models.CharField(default='France', max_length=500)),
                ('activite', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='constructeurs.activite')),
            ],
            options={
                'verbose_name': 'Constructeurs',
            },
        ),
        migrations.CreateModel(
            name='MediaCommunications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.CharField(max_length=500)),
                ('identification', models.CharField(max_length=200)),
                ('complement', models.CharField(max_length=500)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constructeurs.entreprise')),
            ],
        ),
    ]
