# Generated by Django 4.2 on 2023-05-11 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructeurs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entreprise',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
    ]
