# Generated by Django 4.2 on 2023-05-24 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructeurs', '0002_entreprise_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreprise',
            name='bureau_distributeur',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='cedex',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='code_chantier',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='cplt_geo',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='departement',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='lieu_dit',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='pays',
            field=models.CharField(default='France', max_length=20),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='province',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='raison_social',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='ville',
            field=models.CharField(max_length=20),
        ),
    ]
