# Generated by Django 4.2 on 2023-05-30 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructeurs', '0003_alter_entreprise_bureau_distributeur_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entreprise',
            old_name='code_postal_pour_envoie_mail',
            new_name='code_postal',
        ),
        migrations.RemoveField(
            model_name='entreprise',
            name='boite_postal',
        ),
        migrations.RemoveField(
            model_name='entreprise',
            name='bureau_distributeur',
        ),
        migrations.RemoveField(
            model_name='entreprise',
            name='cedex',
        ),
        migrations.RemoveField(
            model_name='entreprise',
            name='courrier',
        ),
        migrations.RemoveField(
            model_name='entreprise',
            name='cp',
        ),
        migrations.RemoveField(
            model_name='entreprise',
            name='cplt_geo',
        ),
        migrations.RemoveField(
            model_name='entreprise',
            name='mel',
        ),
        migrations.AddField(
            model_name='entreprise',
            name='address',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='first_name',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='last_name',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='entreprise',
            name='telephone_fixe',
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='departement',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='fax',
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='lieu_dit',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='numero_siret',
            field=models.CharField(max_length=14),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='province',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='raison_social',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='ville',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
