# Generated by Django 4.2 on 2023-04-19 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0001_initial'),
        ('affaires', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planaffairecreation',
            name='missions',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='missions.missions'),
            preserve_default=False,
        ),
    ]
