# Generated by Django 4.2 on 2023-04-19 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affaires', '0002_planaffairecreation_missions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planaffairecreation',
            name='debut_du_chantier',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='planaffairecreation',
            name='fin_du_chantier',
            field=models.DateField(blank=True),
        ),
    ]
