# Generated by Django 4.2 on 2023-05-01 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affaires', '0003_alter_planaffairecreation_debut_du_chantier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planaffairecreation',
            name='numero_contrat_provisoire',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
