# Generated by Django 4.2 on 2023-05-12 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affaires', '0006_remove_planaffairecreation_missions_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlanAffaireCreation',
        ),
    ]
