# Generated by Django 4.2 on 2023-05-10 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('IT', '0003_rename_cb_propose_interventiontechnique_num_service_propose_and_more'),
        ('Aso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourriersTechniques',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume_courrier', models.CharField(max_length=250, verbose_name='Courrier N°')),
                ('date_emission', models.DateField()),
                ('objet', models.CharField(max_length=500)),
                ('a_suivre', models.BooleanField(default=True)),
                ('aso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Aso.aso')),
                ('intervention_techiniques', models.ManyToManyField(to='IT.interventiontechnique')),
            ],
        ),
    ]
