# Generated by Django 4.2 on 2023-05-17 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aso', '0009_syntheseavis'),
        ('IT', '0004_interventiontechniques_and_more'),
        ('Courriers', '0002_courrierstechniques_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourriersTechniques',
            new_name='Courriers',
        ),
    ]
