# Generated by Django 4.2 on 2023-04-18 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SERVICES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_services', models.CharField(max_length=10)),
                ('nom_services', models.CharField(max_length=500)),
                ('implantation', models.CharField(max_length=200)),
                ('pays', models.CharField(default='France', max_length=500)),
            ],
        ),
    ]
