# Generated by Django 4.2 on 2023-05-24 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='code_services',
            field=models.IntegerField(max_length=10),
        ),
    ]
