# Generated by Django 4.2 on 2023-05-08 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Ouvrages', '0001_initial'),
        ('IT', '0003_rename_cb_propose_interventiontechnique_num_service_propose_and_more'),
        ('constructeurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dossier', models.CharField(default='Exécution', max_length=200)),
                ('nature', models.CharField(default='Plan', max_length=20)),
                ('numero_externe', models.IntegerField(verbose_name='N° Externe')),
                ('numero_aleatek', models.IntegerField()),
                ('date_de_indice', models.DateField()),
                ('date_de_reception', models.DateField()),
                ('indice', models.CharField(max_length=5)),
                ('titre', models.CharField(max_length=500)),
                ('num_revision', models.CharField(default=1, max_length=20, verbose_name='N° révision')),
                ('emetteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constructeurs.entreprise')),
            ],
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_avis', models.CharField(max_length=20)),
                ('avis', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='FichierAttache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prioritaire', models.BooleanField(default=False)),
                ('nom_fichier', models.CharField(max_length=250)),
                ('fichier', models.FileField(upload_to='fichierattachedocument')),
                ('cree_le', models.DateField()),
                ('action', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Revisions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_revision', models.IntegerField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Document.documents')),
            ],
        ),
        migrations.CreateModel(
            name='OuvragesAsscieDocumentConstructeurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constructeurs', models.ManyToManyField(to='constructeurs.entreprise')),
                ('document', models.ManyToManyField(to='Document.documents')),
                ('ouvrages', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ouvrages.ouvrages')),
            ],
        ),
        migrations.AddField(
            model_name='documents',
            name='examen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Document.examen'),
        ),
        migrations.AddField(
            model_name='documents',
            name='fichier_attache',
            field=models.ManyToManyField(blank=True, to='Document.fichierattache'),
        ),
        migrations.AddField(
            model_name='documents',
            name='ouvrage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Documents', to='Ouvrages.ouvrages'),
        ),
        migrations.CreateModel(
            name='AffectationItDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ManyToManyField(to='Document.documents')),
                ('intervention_techniques', models.ManyToManyField(to='IT.interventiontechnique')),
            ],
        ),
    ]
