# Generated by Django 4.2 on 2023-05-12 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Document', '0002_examen_num_avis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examen',
            name='num_avis',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
