# Generated by Django 4.2 on 2023-05-12 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Document', '0003_alter_examen_num_avis'),
    ]

    operations = [
        migrations.AddField(
            model_name='examen',
            name='a_suivre',
            field=models.BooleanField(default=False),
        ),
    ]
