# Generated by Django 4.2 on 2023-05-17 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Document', '0004_examen_a_suivre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examen',
            name='avis',
            field=models.CharField(choices=[('F', 'Favorable'), ('RMQ', 'Remarque'), ('FA', 'Favorable avec avis'), ('HM', 'Hors mission'), ('SO', 'Sans - objet'), ('VI', 'vu pour information')], max_length=20),
        ),
    ]
