# Generated by Django 4.2 on 2023-05-18 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Document', '0005_alter_examen_avis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documents',
            name='examen',
        ),
    ]
