# Generated by Django 4.2 on 2023-05-20 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IT', '0004_interventiontechniques_and_more'),
        ('constructeurs', '0002_entreprise_email'),
        ('Document', '0006_remove_documents_examen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_avis', models.CharField(blank=True, max_length=10)),
                ('avis', models.CharField(choices=[('F', 'F'), ('RMQ', 'RMQ'), ('FA', 'FA'), ('HM', 'HM'), ('SO', 'SO'), ('VI', 'VI')], max_length=20)),
                ('commentaire', models.TextField(max_length=500)),
                ('a_suivre', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='affectationitdocument',
            name='document',
        ),
        migrations.RemoveField(
            model_name='affectationitdocument',
            name='intervention_techniques',
        ),
        migrations.DeleteModel(
            name='Examen',
        ),
        migrations.RemoveField(
            model_name='ouvragesassciedocumentconstructeurs',
            name='constructeurs',
        ),
        migrations.RemoveField(
            model_name='ouvragesassciedocumentconstructeurs',
            name='document',
        ),
        migrations.RemoveField(
            model_name='ouvragesassciedocumentconstructeurs',
            name='ouvrages',
        ),
        migrations.RemoveField(
            model_name='revisions',
            name='document',
        ),
        migrations.AddField(
            model_name='documents',
            name='constructeurs',
            field=models.ManyToManyField(related_name='documents', to='constructeurs.entreprise'),
        ),
        migrations.AddField(
            model_name='documents',
            name='intervention_techniques',
            field=models.ManyToManyField(to='IT.interventiontechniqueassocie'),
        ),
        migrations.AddField(
            model_name='documents',
            name='numero_revision',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='documents',
            name='emetteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Documentss', to='constructeurs.entreprise'),
        ),
        migrations.DeleteModel(
            name='AffectationItDocument',
        ),
        migrations.DeleteModel(
            name='OuvragesAsscieDocumentConstructeurs',
        ),
        migrations.DeleteModel(
            name='Revisions',
        ),
        migrations.AddField(
            model_name='avis',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Document.documents'),
        ),
    ]
