# Generated by Django 4.2 on 2023-05-24 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dashbord', '0019_alter_planaffaire_affaire_alter_planaffaire_produit'),
        ('collaborateurs', '0011_remove_collaborateurs_user'),
        ('Document', '0008_remove_avis_document_remove_documents_constructeurs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='numero_aleatek',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Dashbord.affaires'),
        ),
        migrations.CreateModel(
            name='AffectationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affecte_le', models.DateField()),
                ('action', models.BooleanField(default=True)),
                ('affecte_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collaborateurs.collaborateurs')),
                ('document', models.ManyToManyField(to='Document.documents')),
            ],
        ),
    ]
