# Generated by Django 4.2 on 2023-05-24 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Document', '0009_alter_documents_numero_aleatek_affectationdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='exam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Document.avis'),
        ),
    ]
