# Generated by Django 4.2 on 2023-05-25 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Document', '0010_alter_affectationdocument_affecte_a'),
        ('Document', '0010_alter_documents_exam'),
    ]

    operations = [
    ]
