# Generated by Django 4.2 on 2023-05-25 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Document', '0012_documents_collaborateurs_delete_affectationdocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avis',
            name='num_avis',
        ),
    ]
