# Generated by Django 4.2 on 2023-05-25 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT', '0008_alter_interventiontechniqueassocie_cod_it_and_more'),
        ('Document', '0014_alter_documents_collaborateurs'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='intervention_technique',
            field=models.ManyToManyField(to='IT.interventiontechniqueassocie'),
        ),
    ]
