# Generated by Django 4.2 on 2023-05-25 20:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT', '0008_alter_interventiontechniqueassocie_cod_it_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Document', '0015_documents_intervention_technique'),
    ]

    operations = [
        migrations.AddField(
            model_name='avis',
            name='collaborateurs',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='avis',
            name='valide',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='documents',
            name='dossier',
            field=models.CharField(choices=[('Execution', 'Execution'), ('Concdption', 'Conception')], default='Execution', max_length=200),
        ),
        migrations.CreateModel(
            name='IntervenantInterventionDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affecte_le', models.DateField()),
                ('action', models.BooleanField(default=False)),
                ('intervenant', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('intervention_technique', models.ManyToManyField(to='IT.interventiontechniqueassocie')),
            ],
        ),
        migrations.AddField(
            model_name='documents',
            name='affectation',
            field=models.ManyToManyField(to='Document.intervenantinterventiondocument'),
        ),
    ]
