# Generated by Django 4.2 on 2023-05-25 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Document', '0016_avis_collaborateurs_avis_valide_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documents',
            name='numero_revision',
        ),
    ]
