# Generated by Django 4.2 on 2023-05-25 23:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Document', '0017_remove_documents_numero_revision'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documents',
            name='collaborateurs',
        ),
        migrations.RemoveField(
            model_name='documents',
            name='intervention_technique',
        ),
        migrations.AddField(
            model_name='intervenantinterventiondocument',
            name='affecte_par',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='IntervenantInterventionDocuments', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='avis',
            name='collaborateurs',
        ),
        migrations.RemoveField(
            model_name='documents',
            name='exam',
        ),
        migrations.AddField(
            model_name='avis',
            name='collaborateurs',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documents',
            name='exam',
            field=models.ManyToManyField(to='Document.avis'),
        ),
    ]
