# Generated by Django 4.2 on 2023-05-27 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Document', '0018_remove_documents_collaborateurs_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_suivre', models.BooleanField(default=False)),
                ('commentaire', models.TextField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='avis',
            name='a_suivre',
        ),
        migrations.AddField(
            model_name='documents',
            name='codification',
            field=models.CharField(choices=[('F', 'F'), ('RMQ', 'RMQ'), ('FA', 'FA'), ('HM', 'HM'), ('SO', 'SO'), ('VI', 'VI')], default='', max_length=3),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='avis',
            name='commentaire',
        ),
        migrations.AddField(
            model_name='avis',
            name='commentaire',
            field=models.ManyToManyField(to='Document.commentaire'),
        ),
    ]
