# Generated by Django 4.2 on 2023-05-29 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Document', '0023_alter_documents_validateur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='nature',
            field=models.CharField(choices=[('TOUS', 'TOUS'), ('Descriptif', 'Descriptif'), ('AT/DTA', 'AT/DTA'), ('Attestation Incendie', 'Attestation Incendie'), ('Carnet', 'Carnet'), ('Certificat', 'Certificat'), ('Certificat incendie', 'Certificat incendie'), ('Compte rendue', 'Compte rendu'), ('Courrier', 'Courrier'), ('fiche techinique', 'Fiche Technique'), ('Note', 'Note'), ('Note de calcule', 'Note de calcule'), ('Notice', 'Notice'), ('Plan', 'Plan'), ('PV', 'PV'), ('PV incendie', 'PV Incendie'), ('Rapport', 'Rapport'), ('Schéma', 'Schéma')], default='Plan', max_length=20),
        ),
    ]
