# Generated by Django 4.2 on 2023-05-29 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Document', '0024_alter_documents_nature'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentaire',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='documents',
            name='nos_reference',
            field=models.CharField(default='', max_length=500),
        ),
    ]
