# Generated by Django 4.2 on 2023-05-30 01:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Document', '0025_commentaire_image_documents_nos_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='validateur',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Documents', to=settings.AUTH_USER_MODEL),
        ),
    ]
