# Generated by Django 4.2 on 2023-05-10 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Ouvrages', '0001_initial'),
        ('constructeurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ASO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aso_num', models.CharField(max_length=30, verbose_name='ASO N°')),
                ('date', models.DateField()),
                ('nos_reference', models.CharField(max_length=500)),
                ('dossier', models.CharField(default='Exécution', max_length=500)),
                ('balise_a_solder', models.CharField(max_length=500)),
                ('etape', models.CharField(choices=[('En cours de saisi', 'En cours de saisi'), ('Accepté', 'Accepté'), ('Classé', 'Classé'), ('Préparé', 'Préparé')], max_length=50)),
                ('imprime', models.BooleanField(default=False)),
                ('mel', models.BooleanField(default=False)),
                ('fax', models.BooleanField(default=False)),
                ('edossier', models.BooleanField(default=False)),
                ('armoire', models.BooleanField(default=False)),
                ('maestro', models.BooleanField(default=False)),
                ('avis_ouvrages', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ouvrages.avisouvrages')),
                ('liste_de_diffusion', models.ManyToManyField(to='constructeurs.entreprise')),
                ('ouvrages', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ouvrages.ouvrages')),
            ],
        ),
    ]
