# Generated by Django 4.2 on 2023-05-12 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Document', '0001_initial'),
        ('Aso', '0002_alter_aso_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='aso',
            name='document',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Document.documents'),
            preserve_default=False,
        ),
    ]
