# Generated by Django 4.2 on 2023-05-12 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aso', '0003_aso_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aso',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
