# Generated by Django 4.2 on 2023-05-12 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ouvrages', '0001_initial'),
        ('Aso', '0004_alter_aso_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aso',
            name='avis_ouvrages',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Ouvrages.avisouvrages'),
        ),
    ]
