# Generated by Django 4.2 on 2023-05-12 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aso', '0005_alter_aso_avis_ouvrages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aso',
            old_name='avis_ouvrages',
            new_name='avis_ouvrage',
        ),
    ]
