# Generated by Django 4.2 on 2023-05-12 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aso', '0007_remove_aso_ouvrages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aso',
            name='aso_num',
            field=models.CharField(blank=True, max_length=30, verbose_name='ASO N°'),
        ),
    ]
