# Generated by Django 4.2 on 2023-05-17 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aso', '0008_alter_aso_aso_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyntheseAvis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(max_length=10)),
                ('remarque', models.CharField(max_length=100)),
                ('reformuler', models.CharField(max_length=100)),
                ('exprimer_sur', models.CharField(max_length=100)),
                ('objet_du_controle', models.CharField(max_length=100)),
                ('phase', models.CharField(max_length=100)),
                ('verificateur', models.CharField(max_length=100)),
                ('ouvrages', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
    ]
