# Generated by Django 4.2 on 2023-05-25 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aso', '0009_syntheseavis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aso',
            name='aso_num',
            field=models.IntegerField(blank=True, verbose_name='ASO N°'),
        ),
    ]
