# Generated by Django 4.2 on 2023-05-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='city',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='country',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='client',
            name='postal_code',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='client',
            name='state',
            field=models.CharField(max_length=20),
        ),
    ]
