# Generated by Django 4.2 on 2023-05-11 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_alter_client_address_alter_client_city_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Media',
        ),
    ]
