# Generated by Django 4.2 on 2023-05-08 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ouvrages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='OuvragesDiffusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diffusion_systematique', models.BooleanField(default=False)),
                ('activite', models.CharField(max_length=500)),
                ('libelle', models.CharField(max_length=500, verbose_name='Libelle du lot/chantier')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ouvrages.ouvrages')),
            ],
        ),
        migrations.CreateModel(
            name='AvisOuvrages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avis', models.CharField(max_length=500)),
                ('ouvrages', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ouvrages.ouvrages')),
            ],
        ),
    ]
