# Generated by Django 4.2 on 2023-05-21 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ouvrages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avisouvrages',
            old_name='avis',
            new_name='commentaire',
        ),
    ]
