# Generated by Django 4.2 on 2023-05-24 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ouvrages', '0002_rename_avis_avisouvrages_commentaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ouvrages',
            name='libelle',
            field=models.CharField(max_length=20),
        ),
    ]
