# Generated by Django 4.2 on 2023-05-29 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ouvrages', '0003_alter_ouvrages_libelle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ouvragesdiffusion',
            old_name='designation',
            new_name='ouvrage_type',
        ),
        migrations.RemoveField(
            model_name='ouvragesdiffusion',
            name='libelle',
        ),
        migrations.AddField(
            model_name='ouvragesdiffusion',
            name='a_risque',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ouvragesdiffusion',
            name='code_ged',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='ouvragesdiffusion',
            name='ouvrages_diffusion',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='ouvragesdiffusion',
            name='activite',
            field=models.CharField(max_length=50),
        ),
    ]
