# Generated by Django 4.2 on 2023-05-29 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ouvrages', '0004_rename_designation_ouvragesdiffusion_ouvrage_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avisouvrages',
            name='image',
            field=models.ImageField(default='', upload_to='imageOuvrage'),
        ),
    ]
