# Generated by Django 4.2 on 2023-05-30 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructeurs', '0003_alter_entreprise_bureau_distributeur_and_more'),
        ('Ouvrages', '0005_avisouvrages_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ouvrages',
            name='contructeurs',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='constructeurs.entreprise'),
        ),
    ]
