# Generated by Django 4.2 on 2023-05-30 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ouvrages', '0006_ouvrages_contructeurs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ouvrages',
            name='contructeurs',
        ),
    ]
