# Generated by Django 4.2 on 2023-05-30 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructeurs', '0004_rename_code_postal_pour_envoie_mail_entreprise_code_postal_and_more'),
        ('Ouvrages', '0007_remove_ouvrages_contructeurs'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntrepriseAssocieOuvrages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diffusion_systematique', models.BooleanField(default=False)),
                ('activite', models.CharField(max_length=20)),
                ('libelle_lot', models.CharField(max_length=30)),
                ('type_douvrage', models.CharField(max_length=20)),
                ('types', models.CharField(max_length=20)),
                ('constructeurs', models.ManyToManyField(to='constructeurs.entreprise')),
                ('tableau_diffusion', models.ManyToManyField(related_name='entreprisesovrages', to='constructeurs.entreprise')),
            ],
        ),
    ]
