# Generated by Django 4.2 on 2023-05-12 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collaborateurs', '0002_alter_collaborateurs_address_and_more'),
        ('Media', '0002_remove_media_media_media_name_alter_media_complement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='client',
        ),
        migrations.AddField(
            model_name='media',
            name='charg_affaire',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='collaborateurs.collaborateurs'),
            preserve_default=False,
        ),
    ]
